spring:
  application:
    name: mycipherbook
  datasource:
    url: jdbc:mysql://localhost:3306/cipher_book
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Root@123
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/*/*.xml